plugins {
    id 'com.android.application'
}

android {
    namespace 'com.aarvexa.erp'
    compileSdk 34

    defaultConfig {
        applicationId 'com.aarvexa.erp'
        minSdk 24
        targetSdk 34
        versionCode 16
        versionName '16.0'

        buildConfigField 'String', 'ERP_URL', '"https://aarvexaimf.com/"'
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
